import type { GasEnumDefinition } from "../../globals/enum";

export const spreadsheetEnumDefinitions = {
  AutoFillSeries: {
    members: ["DEFAULT_SERIES", "ALTERNATE_SERIES"],
    representative: "DEFAULT_SERIES",
  },
  BandingTheme: {
    members: [
      "LIGHT_GREY",
      "CYAN",
      "GREEN",
      "YELLOW",
      "ORANGE",
      "BLUE",
      "TEAL",
      "GREY",
      "BROWN",
      "LIGHT_GREEN",
      "INDIGO",
      "PINK",
    ],
    representative: "LIGHT_GREY",
  },
  BooleanCriteria: {
    members: [
      "CELL_EMPTY",
      "CELL_NOT_EMPTY",
      "DATE_AFTER",
      "DATE_BEFORE",
      "DATE_EQUAL_TO",
      "DATE_NOT_EQUAL_TO",
      "DATE_AFTER_RELATIVE",
      "DATE_BEFORE_RELATIVE",
      "DATE_EQUAL_TO_RELATIVE",
      "NUMBER_BETWEEN",
      "NUMBER_EQUAL_TO",
      "NUMBER_GREATER_THAN",
      "NUMBER_GREATER_THAN_OR_EQUAL_TO",
      "NUMBER_LESS_THAN",
      "NUMBER_LESS_THAN_OR_EQUAL_TO",
      "NUMBER_NOT_BETWEEN",
      "NUMBER_NOT_EQUAL_TO",
      "TEXT_CONTAINS",
      "TEXT_DOES_NOT_CONTAIN",
      "TEXT_EQUAL_TO",
      "TEXT_NOT_EQUAL_TO",
      "TEXT_STARTS_WITH",
      "TEXT_ENDS_WITH",
      "CUSTOM_FORMULA",
    ],
    representative: "NUMBER_BETWEEN",
  },
  BorderStyle: {
    members: ["DOTTED", "DASHED", "SOLID", "SOLID_MEDIUM", "SOLID_THICK", "DOUBLE"],
    representative: "SOLID",
  },
  ChartAggregationType: {
    members: ["UNSUPPORTED", "AVERAGE", "COUNT", "MAX", "MEDIAN", "MIN", "SUM"],
    representative: "UNSUPPORTED",
  },
  ChartTransformationType: {
    members: [
      "CHART_TRANSFORMATION_TYPE_UNSUPPORTED",
      "AGGREGATION",
      "CHART_FILTER",
      "FORM_AGGREGATE",
      "SORT",
    ],
    representative: "CHART_TRANSFORMATION_TYPE_UNSUPPORTED",
  },
  ColorType: {
    members: ["UNSUPPORTED", "RGB", "THEME"],
    representative: "UNSUPPORTED",
  },
  CopyPasteType: {
    members: [
      "PASTE_NORMAL",
      "PASTE_NO_BORDERS",
      "PASTE_FORMAT",
      "PASTE_FORMULA",
      "PASTE_DATA_VALIDATION",
      "PASTE_VALUES",
      "PASTE_CONDITIONAL_FORMATTING",
      "PASTE_COLUMN_WIDTHS",
    ],
    representative: "PASTE_NORMAL",
  },
  DataExecutionErrorCode: {
    members: [
      "DATA_EXECUTION_ERROR_CODE_UNSUPPORTED",
      "NONE",
      "TIME_OUT",
      "TOO_MANY_ROWS",
      "TOO_MANY_COLUMNS",
      "TOO_MANY_CELLS",
      "ENGINE",
      "PARAMETER_INVALID",
      "UNSUPPORTED_DATA_TYPE",
      "DUPLICATE_COLUMN_NAMES",
      "INTERRUPTED",
      "OTHER",
      "TOO_MANY_CHARS_PER_CELL",
      "DATA_NOT_FOUND",
      "PERMISSION_DENIED",
    ],
    representative: "NONE",
  },
  DataExecutionState: {
    members: ["DATA_EXECUTION_STATE_UNSUPPORTED", "RUNNING", "SUCCESS", "ERROR", "NOT_STARTED"],
    representative: "SUCCESS",
  },
  DataSourceParameterType: {
    members: ["DATA_SOURCE_PARAMETER_TYPE_UNSUPPORTED", "CELL"],
    representative: "CELL",
  },
  DataSourceRefreshScope: {
    members: ["DATA_SOURCE_REFRESH_SCOPE_UNSUPPORTED", "ALL_DATA_SOURCES"],
    representative: "DATA_SOURCE_REFRESH_SCOPE_UNSUPPORTED",
  },
  DataSourceType: {
    members: ["DATA_SOURCE_TYPE_UNSUPPORTED", "BIGQUERY", "LOOKER"],
    representative: "BIGQUERY",
  },
  DataValidationCriteria: {
    members: [
      "DATE_AFTER",
      "DATE_BEFORE",
      "DATE_BETWEEN",
      "DATE_EQUAL_TO",
      "DATE_IS_VALID_DATE",
      "DATE_NOT_BETWEEN",
      "DATE_ON_OR_AFTER",
      "DATE_ON_OR_BEFORE",
      "NUMBER_BETWEEN",
      "NUMBER_EQUAL_TO",
      "NUMBER_GREATER_THAN",
      "NUMBER_GREATER_THAN_OR_EQUAL_TO",
      "NUMBER_LESS_THAN",
      "NUMBER_LESS_THAN_OR_EQUAL_TO",
      "NUMBER_NOT_BETWEEN",
      "NUMBER_NOT_EQUAL_TO",
      "TEXT_CONTAINS",
      "TEXT_DOES_NOT_CONTAIN",
      "TEXT_EQUAL_TO",
      "TEXT_IS_VALID_EMAIL",
      "TEXT_IS_VALID_URL",
      "VALUE_IN_LIST",
      "VALUE_IN_RANGE",
      "CUSTOM_FORMULA",
      "CHECKBOX",
      "DATE_AFTER_RELATIVE",
      "DATE_BEFORE_RELATIVE",
      "DATE_EQUAL_TO_RELATIVE",
    ],
    representative: "NUMBER_BETWEEN",
  },
  DateTimeGroupingRuleType: {
    members: [
      "UNSUPPORTED",
      "SECOND",
      "MINUTE",
      "HOUR",
      "HOUR_MINUTE",
      "HOUR_MINUTE_AMPM",
      "DAY_OF_WEEK",
      "DAY_OF_YEAR",
      "DAY_OF_MONTH",
      "DAY_MONTH",
      "MONTH",
      "QUARTER",
      "YEAR",
      "YEAR_MONTH",
      "YEAR_QUARTER",
      "YEAR_MONTH_DAY",
    ],
    representative: "UNSUPPORTED",
  },
  DeveloperMetadataLocationType: {
    members: ["SPREADSHEET", "SHEET", "ROW", "COLUMN"],
    representative: "SPREADSHEET",
  },
  DeveloperMetadataVisibility: {
    members: ["DOCUMENT", "PROJECT"],
    representative: "DOCUMENT",
  },
  Dimension: {
    members: ["COLUMNS", "ROWS"],
    representative: "COLUMNS",
  },
  Direction: {
    members: ["UP", "DOWN", "PREVIOUS", "NEXT"],
    representative: "UP",
  },
  FrequencyType: {
    members: ["FREQUENCY_TYPE_UNSUPPORTED", "HOURLY", "DAILY", "WEEKLY", "MONTHLY"],
    representative: "FREQUENCY_TYPE_UNSUPPORTED",
  },
  GroupControlTogglePosition: {
    members: ["BEFORE", "AFTER"],
    representative: "AFTER",
  },
  InterpolationType: {
    members: ["NUMBER", "PERCENT", "PERCENTILE", "MIN", "MAX"],
    representative: "NUMBER",
  },
  PivotTableSummarizeFunction: {
    members: [
      "CUSTOM",
      "SUM",
      "COUNTA",
      "COUNT",
      "COUNTUNIQUE",
      "AVERAGE",
      "MAX",
      "MIN",
      "MEDIAN",
      "PRODUCT",
      "STDEV",
      "STDEVP",
      "VAR",
      "VARP",
    ],
    representative: "SUM",
  },
  PivotValueDisplayType: {
    members: [
      "DEFAULT",
      "PERCENT_OF_ROW_TOTAL",
      "PERCENT_OF_COLUMN_TOTAL",
      "PERCENT_OF_GRAND_TOTAL",
    ],
    representative: "DEFAULT",
  },
  ProtectionType: {
    members: ["RANGE", "SHEET"],
    representative: "RANGE",
  },
  RecalculationInterval: {
    members: ["ON_CHANGE", "MINUTE", "HOUR"],
    representative: "ON_CHANGE",
  },
  RelativeDate: {
    members: ["TODAY", "TOMORROW", "YESTERDAY", "PAST_WEEK", "PAST_MONTH", "PAST_YEAR"],
    representative: "TODAY",
  },
  SheetType: {
    members: ["GRID", "OBJECT", "DATASOURCE"],
    representative: "GRID",
  },
  SortOrder: {
    members: ["ASCENDING", "DESCENDING"],
    representative: "ASCENDING",
  },
  TextDirection: {
    members: ["LEFT_TO_RIGHT", "RIGHT_TO_LEFT"],
    representative: "LEFT_TO_RIGHT",
  },
  TextToColumnsDelimiter: {
    members: ["COMMA", "SEMICOLON", "PERIOD", "SPACE"],
    representative: "COMMA",
  },
  ThemeColorType: {
    members: [
      "UNSUPPORTED",
      "TEXT",
      "BACKGROUND",
      "ACCENT1",
      "ACCENT2",
      "ACCENT3",
      "ACCENT4",
      "ACCENT5",
      "ACCENT6",
      "HYPERLINK",
    ],
    representative: "UNSUPPORTED",
  },
  ValueType: {
    members: ["IMAGE"],
    representative: "IMAGE",
  },
  WrapStrategy: {
    members: ["WRAP", "OVERFLOW", "CLIP"],
    representative: "WRAP",
  },
} as const satisfies Record<string, GasEnumDefinition<string>>;
