name: ci
on:
  push:
    branches:
      - main
      # - develop
  pull_request:
    branches:
      - main
      # - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/setup@v2
        with:
          runtime: "node@22.12"
          cache: true
      - run: pnpm check
